apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-haproxy
  name: mc-haproxy
  annotations:
    configmap.reloader.stakater.com/reload: "haproxy-config"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mc-server-test
  template:
    metadata:
      labels:
        app: mc-server-test
    spec:
      containers:
          image: haproxy:2.9-dev8-alpine3.18
          name: mc-server-test
          ports:
            - containerPort: 25565
              name: mc-main
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
