apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  annotations:
    configmap.reloader.stakater.com/reload: "nginx-config"
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:alpine3.18-slim
          name: nginx
          ports:
            - name: nginx
              containerPort: 80
            - name: nginxs
              containerPort: 443
          # startupProbe:
          #   tcpSocket:
          #     port: 25577
          #   # 最大120秒待つ
          #   failureThreshold: 6
          #   periodSeconds: 20
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
