apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tikiba
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - guest
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: VOLUME_ID
    volumeAttributes:
      source: "//100.64.10.131/tikiba"
    # nodeStageSecretRef:
    #   name: SECRET_NAME
    #   namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tikiba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-tikiba
  storageClassName: ""
