apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-server-test-vscode-config
data:
  config.yaml : |
    bind-addr: 0.0.0.0:8080
    auth: password
    password: 71ace077ba99d5522ec155bb
    cert: false
