# bungeecordの長期起動によるスローダウンを防止するための定期再起動を担うScaledObject
# scaledobjectの仕様上厳密には停止して起動する
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject-mc-tikiba-survival
spec:
  scaleTargetRef:
    name: mc-tikiba-survival
    kind: Deployment
  # 再起動の時間に極力添えるようにチェックは毎回行うようにさせる
  pollingInterval:  30
  cooldownPeriod:   30
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Tokyo
      # "月: 04:06 (https://crontab.guru/)
      start: 1 12 * * *
      end: 0 12 * * *
      desiredReplicas: '1'
  minReplicaCount: 0 # 何も条件がない場合はスケール数が minReplicaCount になる(cronが発火している間イベント駆動で desiredReplicas にスケール)
  maxReplicaCount: 1
