apiVersion: v1
kind: Service
metadata:
  name: mc-tikiba-svc
spec:
  selector:
    app: mc-tikiba
  ports:
  - name: mc-tikiba
    port: 25565
    targetPort: mc-tikiba
  - name: mc-tikiba-rcon
    port: 25575
    targetPort: mc-tikiba-rcon