apiVersion: v1
kind: Service
metadata:
  name: mc-server-poteto-svc
spec:
  selector:
    app: mc-server-poteto
  ports:
  - name: mc
    port: 25565
    targetPort: mc-poteto
  - name: code
    port: 80
    targetPort: mc-poteto-code
