apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
  - port: 80
    targetPort: registry
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
  annotations:
    configmap.reloader.stakater.com/reload: "velocity-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          ports:
            - name: registry
              containerPort: 5000
          volumeMounts:
            - name: registry
              mountPath: /var/lib/registry
        - name: registry-ui
          image: joxit/docker-registry-ui:2
          env:
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: "true"
            - name: SHOW_CONTENT_DIGEST
              value: "true"
            - name: NGINX_PROXY_PASS_URL
              value: "http://registry"
            - name: REGISTRY_SECURED
              value: "false"
          volumeMounts:
            - name: registry-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - name: registry-ui
              containerPort: 80
      volumes:
        - name: registry
        - name: registry-nginx
          configMap:
            name: registry-nginx
