apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: LoadBalancer
  ports:
    - name: registry-ui
      port: 80
      protocol: TCP
      targetPort: registry-ui
  selector:
    app: registry
