apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-tikiba-lobby
data:
  paper-global.yml: |
    _version: 28
    block-updates:
      disable-chorus-plant-updates: false
      disable-mushroom-block-updates: false
      disable-noteblock-updates: false
      disable-tripwire-updates: false
    chunk-loading-advanced:
      auto-config-send-distance: true
      player-max-concurrent-chunk-generates: 0
      player-max-concurrent-chunk-loads: 0
    chunk-loading-basic:
      player-max-chunk-generate-rate: -1.0
      player-max-chunk-load-rate: 100.0
      player-max-chunk-send-rate: 75.0
    chunk-system:
      gen-parallelism: default
      io-threads: -1
      worker-threads: -1
    collisions:
      enable-player-collisions: true
      send-full-pos-for-hard-colliding-entities: true
    commands:
      fix-target-selector-tag-completion: true
      suggest-player-names-when-null-tab-completions: true
      time-command-affects-all-worlds: false
    console:
      enable-brigadier-completions: true
      enable-brigadier-highlighting: true
      has-all-permissions: false
    item-validation:
      book:
        author: 8192
        page: 16384
        title: 8192
      book-size:
        page-max: 2560
        total-multiplier: 0.98
      display-name: 8192
      lore-line: 8192
      resolve-selectors-in-books: false
    logging:
      deobfuscate-stacktraces: true
      log-player-ip-addresses: true
    messages:
      kick:
        authentication-servers-down: <lang:multiplayer.disconnect.authservers_down>
        connection-throttle: Connection throttled! Please wait before reconnecting.
        flying-player: <lang:multiplayer.disconnect.flying>
        flying-vehicle: <lang:multiplayer.disconnect.flying>
      no-permission: <red>I'm sorry, but you do not have permission to perform this command.
        Please contact the server administrators if you believe that this is in error.
      use-display-name-in-quit-message: false
    misc:
      chat-threads:
        chat-executor-core-size: -1
        chat-executor-max-size: -1
      compression-level: default
      fix-entity-position-desync: true
      load-permissions-yml-before-plugins: true
      max-joins-per-tick: 5
      region-file-cache-size: 256
      strict-advancement-dimension-check: false
      use-alternative-luck-formula: false
      use-dimension-type-for-custom-spawners: false
    packet-limiter:
      all-packets:
        action: KICK
        interval: 7.0
        max-packet-rate: 500.0
      kick-message: <red><lang:disconnect.exceeded_packet_rate>
      overrides:
        ServerboundPlaceRecipePacket:
          action: DROP
          interval: 4.0
          max-packet-rate: 5.0
    player-auto-save:
      max-per-tick: -1
      rate: -1
    proxies:
      bungee-cord:
        online-mode: true
      proxy-protocol: false
      velocity:
        enabled: true
        online-mode: false
        secret: 'topi'
    scoreboards:
      save-empty-scoreboard-teams: false
      track-plugin-scoreboards: false
    spam-limiter:
      incoming-packet-threshold: 300
      recipe-spam-increment: 1
      recipe-spam-limit: 20
      tab-spam-increment: 1
      tab-spam-limit: 500
    timings:
      enabled: true
      hidden-config-entries:
      - database
      - proxies.velocity.secret
      history-interval: 300
      history-length: 3600
      server-name: Unknown Server
      server-name-privacy: false
      url: https://timings.aikar.co/
      verbose: true
    unsupported-settings:
      allow-grindstone-overstacking: false
      allow-headless-pistons: false
      allow-permanent-block-break-exploits: false
      allow-piston-duplication: false
      compression-format: ZLIB
      perform-username-validation: true
    watchdog:
      early-warning-delay: 10000
      early-warning-every: 5000
  server.properties: |
    #Minecraft server properties
    #Thu Sep 14 23:40:34 JST 2023
    enable-jmx-monitoring=false
    rcon.port=25575
    level-seed=
    gamemode=creative
    enable-command-block=false
    enable-query=false
    generator-settings={}
    enforce-secure-profile=true
    level-name=world
    motd=A Paper Minecraft Server powered by Docker
    query.port=25565
    pvp=true
    generate-structures=true
    max-chained-neighbor-updates=1000000
    difficulty=peaceful
    network-compression-threshold=256
    max-tick-time=60000
    require-resource-pack=false
    use-native-transport=true
    max-players=20
    online-mode=false
    enable-status=true
    allow-flight=false
    initial-disabled-packs=
    broadcast-rcon-to-ops=true
    view-distance=10
    server-ip=
    resource-pack-prompt=
    allow-nether=true
    server-port=25565
    enable-rcon=true
    sync-chunk-writes=true
    op-permission-level=4
    prevent-proxy-connections=false
    hide-online-players=false
    resource-pack=
    entity-broadcast-range-percentage=100
    simulation-distance=10
    rcon.password=64623f7a5274dddf355b6341
    player-idle-timeout=0
    debug=false
    force-gamemode=false
    rate-limit=0
    hardcore=false
    white-list=false
    broadcast-console-to-ops=true
    spawn-npcs=true
    spawn-animals=true
    function-permission-level=2
    initial-enabled-packs=vanilla
    level-type=minecraft\:normal
    text-filtering-config=
    spawn-monsters=true
    enforce-whitelist=false
    spawn-protection=0 # スポーンチャンク保護
    resource-pack-sha1=
    max-world-size=29999984
  permissions.yml: |
    tabtps.defaultdisplay:
      default: true
